host: 127.0.0.1
port: 8080
development: true
cache_seed: 1

site:
  name: aio-three-template
  copyright: Roberto Prevato
  google_analytics: ''

logs:
  - file : /logs/app.log

postgres:
  database: db_name
  user: db_user
  password: db_password
  host: localhost
  port: 5432
  minsize: 1
  maxsize: 5